"""CoW Protocol Objective and User Surplus Calculator.

Computes exact economic surplus generated by batch settlement solutions,
ranking candidate solutions to maximize user welfare and protocol score.
"""

from decimal import Decimal

from solver.models import AuctionInstance, Order, OrderKind, Solution


class CoWObjectiveCalculator:
    """Calculates user surplus and ranks batch settlement solutions."""

    def calculate_order_surplus(self, order: Order, executed_buy_amount: int) -> int:
        """Compute the surplus for a single order in buy token units."""
        if order.kind == OrderKind.SELL:
            # User gets more buy tokens than minimum limit amount
            return executed_buy_amount - order.buy_amount
        else:
            # User sells fewer tokens than maximum limit amount
            return order.sell_amount - executed_buy_amount

    def score_solution(self, auction: AuctionInstance, solution: Solution) -> int:
        """Compute protocol ranking score based on total user surplus."""
        order_map: dict[str, Order] = {o.uid: o for o in auction.orders}
        total_surplus: int = 0

        for trade in solution.trades:
            order = order_map.get(trade.order_uid)
            if not order:
                continue

            sell_price = solution.prices.get(order.sell_token)
            buy_price = solution.prices.get(order.buy_token)

            if not sell_price or not buy_price or buy_price <= 0:
                continue

            # Calculate executed buy amount based on uniform clearing prices
            # E_buy = E_sell * (P_sell / P_buy)
            executed_buy_amount = int(
                Decimal(trade.executed_amount) * Decimal(sell_price) / Decimal(buy_price)
            )

            surplus = self.calculate_order_surplus(order, executed_buy_amount)
            if surplus <= 0:
                continue

            # Normalize surplus to shared reference price (USD / reference units)
            token_meta = auction.tokens.get(order.buy_token)
            if token_meta and token_meta.reference_price and token_meta.decimals:
                norm_factor = Decimal(token_meta.reference_price) / Decimal(10**token_meta.decimals)
                total_surplus += int(Decimal(surplus) * norm_factor)
            else:
                total_surplus += surplus

        return total_surplus
